name: usb_bot-workflow

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
          pip install -r requirements.txt
      # - name: Test with flake8
      #   run: |
      #     python -m flake8

      - name: Run unit tests
        run: |
          python -m unittest discover -s tests

  build_and_push_to_docker_hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: artemeho/usb_bot:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push_to_docker_hub
    if: github.ref == 'refs/heads/main'
    steps:
      - name: executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            mkdir /home/usb_bot/
            mkdir /home/usb_bot/USB
            cd /home/usb_bot/
            sudo docker container stop usb_bot
            sudo docker pull artemeho/usb_bot:latest
            sudo docker run \
            --mount src="$(pwd)"/USB,target=/app/USB,type=bind \
            --detach \
            --rm \
            --env-file .env \
            --name usb_bot artemeho/usb_bot

  send_message:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: send message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ✅  Успешно выполнен:    ${{ github.workflow }} 

            👨‍💻  ${{ github.actor }} created commit:
            📝 Commit message:    " ${{ github.event.commits[0].message }} "
            🗄  Repository:    ${{ github.repository }}
            👀 See changes:    https://github.com/${{ github.repository }}/commit/${{github.sha}}
